/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Image;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import modelo.Empleado;
import modelo.Horario;

/**
 *
 * @author elias
 */
public class AsignarHorario extends javax.swing.JFrame {
        controlador.Conexion con = new controlador.Conexion();
        Connection cn  = con.conexion();
    /**
     * Creates new form AsignarHorario
     */
    public AsignarHorario() {
        initComponents();
        ImageIcon imagen = new ImageIcon("src/imagen/fondo.jpg");
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(), Image.SCALE_DEFAULT));
        jLabel1.setIcon(icono);
        llenaStatus();
        
    }
    void llenaStatus(){
     CB_Status.removeAllItems();
     CB_Status.addItem("A");
     CB_Status.addItem("I");
}
void llenardatos(){
    txt_cveemp.setEnabled(true);
       // inhabilitar();
        Empleado datosEmpleado;
        datosEmpleado = new Empleado();
        controlador.Consultas consEmps;
        consEmps = new controlador.Consultas();
        Statement st;
        
        try {
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(consEmps.consultaEmpleados(txt_cveemp.getText()));
             while(rs.next()){
            datosEmpleado.setCNOMBRE(rs.getString("cnombre"));
            datosEmpleado.setCAPEUNO(rs.getString("capeuno"));
            datosEmpleado.setCAPEDOS(rs.getString("capedos"));
            datosEmpleado.setNIDESTA(Integer.parseInt(rs.getString("nidesta")));
            txt_nombre.setText(datosEmpleado.getCNOMBRE());
            txt_apeuno.setText(datosEmpleado.getCAPEUNO()+" "+datosEmpleado.getCAPEDOS());
                                   
             }
             } catch (SQLException ex) {
            Logger.getLogger(ConsultaEmpleados.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        
}
void LlenarHorario(){
    Horario datosHorario;
    datosHorario = new Horario();
    controlador.Consultas consHor;
    consHor = new controlador.Consultas();
    Statement st;
    try{
        st = cn.createStatement();
        ResultSet rs = st.executeQuery(consHor.consultaHorario(Integer.parseInt(txt_idhorario.getText())));
            //JOptionPane.showMessageDialog(this, "tercero");
             while(rs.next()){
            datosHorario.setCDESCHR(rs.getString("CDESCHR"));
            datosHorario.setCSTATUS(rs.getString("CSTATUS"));
            txt_hdesc.setText(datosHorario.getCDESCHR());
            JOptionPane.showMessageDialog(this, datosHorario.getCSTATUS().length() );
            if (datosHorario.getCSTATUS() != "I"){
                CB_Status.setSelectedIndex(0);
             }
            if (datosHorario.getCSTATUS().compareTo("A")==0){
                     CB_Status.setSelectedIndex(0);
                     }
            if (datosHorario.getCSTATUS().compareTo("I")==0){
                     CB_Status.setSelectedIndex(1);
                     }
             }
              } catch (SQLException ex) {
            Logger.getLogger(ConsultaEmpleados.class.getName()).log(Level.SEVERE, null, ex);
        }
    
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_cveemp = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        txt_idhorario = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        CB_Status = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txt_apeuno = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_hdesc = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(850, 500));
        setMinimumSize(new java.awt.Dimension(815, 500));
        setPreferredSize(new java.awt.Dimension(815, 500));
        getContentPane().setLayout(null);

        txt_cveemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cveempActionPerformed(evt);
            }
        });
        getContentPane().add(txt_cveemp);
        txt_cveemp.setBounds(150, 28, 130, 30);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Clave");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 40, 28, 20);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombre");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 90, 60, 20);
        getContentPane().add(txt_nombre);
        txt_nombre.setBounds(150, 80, 130, 30);

        txt_idhorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idhorarioActionPerformed(evt);
            }
        });
        getContentPane().add(txt_idhorario);
        txt_idhorario.setBounds(40, 160, 100, 30);

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(150, 160, 69, 24);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Status");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 300, 50, 20);

        CB_Status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CB_Status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB_StatusActionPerformed(evt);
            }
        });
        getContentPane().add(CB_Status);
        CB_Status.setBounds(110, 300, 58, 23);

        jButton2.setText("Inicio");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(50, 400, 80, 24);

        jButton3.setText("Limpiar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(180, 400, 90, 24);

        jButton4.setText("Guardar");
        getContentPane().add(jButton4);
        jButton4.setBounds(330, 400, 90, 24);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Descripcion de Horario");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(400, 140, 130, 30);

        txt_apeuno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_apeunoActionPerformed(evt);
            }
        });
        getContentPane().add(txt_apeuno);
        txt_apeuno.setBounds(540, 30, 170, 30);

        txt_hdesc.setColumns(20);
        txt_hdesc.setRows(5);
        jScrollPane1.setViewportView(txt_hdesc);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(530, 130, 240, 90);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Apellido");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(460, 40, 60, 20);

        jButton5.setText("Consultar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(300, 30, 100, 24);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Id Horario");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(50, 140, 60, 14);

        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 810, 470);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_cveempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cveempActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cveempActionPerformed

    private void txt_idhorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idhorarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idhorarioActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txt_apeunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_apeunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_apeunoActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        llenardatos();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        LlenarHorario();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void CB_StatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB_StatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CB_StatusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AsignarHorario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AsignarHorario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AsignarHorario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AsignarHorario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AsignarHorario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CB_Status;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt_apeuno;
    private javax.swing.JTextField txt_cveemp;
    private javax.swing.JTextArea txt_hdesc;
    private javax.swing.JTextField txt_idhorario;
    private javax.swing.JTextField txt_nombre;
    // End of variables declaration//GEN-END:variables
}
