/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import modelo.*;
import vista.*;
import vista.ConsultaEmpleados;
import vista.Inicio;
import vista.RegistrarEmpleado;
import static vista.RegistrarEmpleado.MYSQL_DUPLICATE_PK;

/**
 *
 * @author elias
 */
public class AsignarHorario extends javax.swing.JFrame {
        controlador.Conexion con = new controlador.Conexion();
        Connection cn  = con.conexion();
    /**
     * Creates new form AsignarHorario
     */
    public AsignarHorario() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Asignar horario");
        ImageIcon imagen = new ImageIcon("src/imagen/fondo.jpg");
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(), Image.SCALE_DEFAULT));
        jLabel1.setIcon(icono);
        llenaStatus();
        
    }
    void llenaStatus(){
     CB_Status.removeAllItems();
     CB_Status.addItem("A");
     CB_Status.addItem("I");
}
void llenardatos(){
    txt_cveemp.setEnabled(true);
       // inhabilitar();
        Empleado datosEmpleado;
        datosEmpleado = new Empleado();
        controlador.Consultas consEmps;
        consEmps = new controlador.Consultas();
        Statement st;
        
        try {
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(consEmps.consultaEmpleados(txt_cveemp.getText()));
             while(rs.next()){
            datosEmpleado.setCNOMBRE(rs.getString("cnombre"));
            datosEmpleado.setCAPEUNO(rs.getString("capeuno"));
            datosEmpleado.setCAPEDOS(rs.getString("capedos"));
            datosEmpleado.setNIDESTA(Integer.parseInt(rs.getString("nidesta")));
            txt_nombre.setText(datosEmpleado.getCNOMBRE()+" "+ datosEmpleado.getCAPEUNO()+" "+datosEmpleado.getCAPEDOS());
            //txt_apeuno.setText(datosEmpleado.getCAPEUNO()+" "+datosEmpleado.getCAPEDOS());
                                   
             }
             } catch (SQLException ex) {
            Logger.getLogger(ConsultaEmpleados.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(txt_nombre.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Empleado no existente");
        }
       
        
}
void LlenarHorario(){
    Horario datosHorario;
    datosHorario = new Horario();
    controlador.Consultas consHor;
    consHor = new controlador.Consultas();
    Statement st;
    try{
        st = cn.createStatement();
        ResultSet rs = st.executeQuery(consHor.consultaHorario(Integer.parseInt(txt_idhorario.getText())));
            //JOptionPane.showMessageDialog(this, "tercero");
             while(rs.next()){
            datosHorario.setCDESCHR(rs.getString("CDESCHR"));
            datosHorario.setCSTATUS(rs.getString("CSTATUS"));
            txt_hdesc.setText(datosHorario.getCDESCHR());
            JOptionPane.showMessageDialog(this, datosHorario.getCSTATUS().length() );
            if (datosHorario.getCSTATUS().compareTo("A")==0){
                     CB_Status.setSelectedIndex(0);
                     }
            if (datosHorario.getCSTATUS().compareTo("I")==0){
                     CB_Status.setSelectedIndex(1);
                     }
             }
              } catch (SQLException ex) {
            Logger.getLogger(ConsultaEmpleados.class.getName()).log(Level.SEVERE, null, ex);
        }
        //if(txt_hdesc.getText().equals("")){
           // JOptionPane.showMessageDialog(null, "Horario no existente");
       // }
    
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_cveemp = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        txt_idhorario = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        CB_Status = new javax.swing.JComboBox<>();
        btnInicio = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_hdesc = new javax.swing.JTextArea();
        jButton5 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(815, 500));
        getContentPane().setLayout(null);

        txt_cveemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cveempActionPerformed(evt);
            }
        });
        getContentPane().add(txt_cveemp);
        txt_cveemp.setBounds(180, 70, 130, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Clave");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 80, 90, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombre empleado");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 130, 140, 20);

        txt_nombre.setEnabled(false);
        getContentPane().add(txt_nombre);
        txt_nombre.setBounds(180, 120, 440, 30);

        txt_idhorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idhorarioActionPerformed(evt);
            }
        });
        getContentPane().add(txt_idhorario);
        txt_idhorario.setBounds(180, 190, 100, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(80, 230, 120, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Status");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 300, 50, 20);

        CB_Status.setEditable(true);
        CB_Status.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        CB_Status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CB_Status.setEnabled(false);
        CB_Status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB_StatusActionPerformed(evt);
            }
        });
        getContentPane().add(CB_Status);
        CB_Status.setBounds(180, 290, 80, 30);

        btnInicio.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnInicio.setText("Inicio");
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });
        getContentPane().add(btnInicio);
        btnInicio.setBounds(180, 380, 100, 30);

        btnLimpiar.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpiar);
        btnLimpiar.setBounds(520, 380, 110, 30);

        btnGuardar.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar);
        btnGuardar.setBounds(350, 380, 110, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Descripcion de Horario");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(400, 170, 240, 40);

        txt_hdesc.setColumns(20);
        txt_hdesc.setRows(5);
        txt_hdesc.setEnabled(false);
        jScrollPane1.setViewportView(txt_hdesc);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(400, 210, 390, 110);

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jButton5.setText("Consultar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(340, 70, 120, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Id Horario");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 190, 90, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Asignar horario");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(320, 20, 150, 23);

        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 810, 470);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_cveempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cveempActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cveempActionPerformed

    private void txt_idhorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idhorarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idhorarioActionPerformed

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        Inicio ini = new Inicio();
        ini.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnInicioActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txt_cveemp.setText("");
        txt_nombre.setText("");
        txt_idhorario.setText("");
        txt_hdesc.setText("");
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        txt_nombre.setText("");
        //txt_apeuno.setText("");
        llenardatos();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        txt_hdesc.setText("");
        LlenarHorario();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void CB_StatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB_StatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CB_StatusActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
       if(txt_nombre.getText().equals("")){
           JOptionPane.showMessageDialog(null, "Por favor ingresa la clave de un usuario existente");
       }else if(txt_hdesc.getText().equals("")){
           JOptionPane.showMessageDialog(null, "Por favor ingrese la clave de un horario existente");
       }else{
            Empleado datoEmp = new Empleado();
            controlador.Inserciones asigHor;
            asigHor = new controlador.Inserciones();
            Horario datoHorario = new Horario();
            datoEmp.setCCVEEMP(txt_cveemp.getText());
            datoHorario.setNIDHORA(Integer.parseInt(txt_idhorario.getText()));
            datoHorario.setCSTATUS(CB_Status.getItemAt(CB_Status.getSelectedIndex()));
            //JOptionPane.showMessageDialog(null, "e"+ datoEmp.getCCVEEMP()+" "+datoHorario.getNIDHORA()+" "+datoHorario.getCSTATUS());
            try{
                PreparedStatement pps = cn.prepareStatement(asigHor.insertAsignarHorarios());
                pps.setInt(1, datoHorario.getNIDHORA());
                pps.setString(2,datoEmp.getCCVEEMP());
                pps.setString(3, datoHorario.getCSTATUS());
                pps.executeUpdate();
                JOptionPane.showMessageDialog(this, "Horario asignado con exito");
                txt_cveemp.setText("");
                txt_nombre.setText("");
                txt_idhorario.setText("");
                txt_hdesc.setText("");
            }catch (SQLException ex) {
            if(ex.getErrorCode() == MYSQL_DUPLICATE_PK ){
                JOptionPane.showMessageDialog(this, "El empleado ya tiene asignado ese horario");
            }
            Logger.getLogger(RegistrarEmpleado.class.getName()).log(Level.SEVERE, null, ex);
        }
       }
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AsignarHorario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AsignarHorario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AsignarHorario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AsignarHorario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AsignarHorario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CB_Status;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt_cveemp;
    private javax.swing.JTextArea txt_hdesc;
    private javax.swing.JTextField txt_idhorario;
    private javax.swing.JTextField txt_nombre;
    // End of variables declaration//GEN-END:variables
}
