/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import modelo.Justificantes;

/**
 *
 * @author Biersack
 */
public class ModJustificante extends javax.swing.JFrame {
    controlador.Conexion con = new controlador.Conexion();
    Connection cn  = con.conexion();

    /**
     * Creates new form ModJustificante
     */
    public ModJustificante() {
        initComponents();
        llenaJustificantes();
        setLocationRelativeTo(null);
        setTitle("Modificar justificante");
        ImageIcon imagen = new ImageIcon("src/imagen/fondo.jpg");
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(), Image.SCALE_DEFAULT));
        jLabel1.setIcon(icono);
    }
    
    void llenaJustificantes(){
    controlador.Consultas consjust;
    consjust = new controlador.Consultas();
        CB_justificante.removeAllItems();
        
        Statement st;
        try {
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(consjust.consultaCatalogoJudtificanteTotal());
            
            while (rs.next()){
                CB_justificante.addItem(rs.getString(1));
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(RegistrarEmpleado.class.getName()).log(Level.SEVERE, null, ex);
        }
        Llenarmotivo(Integer.parseInt(CB_justificante.getItemAt(CB_justificante.getSelectedIndex())));
    }
    void Llenarmotivo(int clave){
    controlador.Consultas consJu;
    consJu = new controlador.Consultas();
    Statement st;
    try{
        st = cn.createStatement();
        ResultSet rs = st.executeQuery(consJu.consutaMotivoJus(clave));
            
             while(rs.next()){
                txt_Motivo.setText(rs.getString(1));
             }
        } catch (SQLException ex) {
            Logger.getLogger(ConsultaEmpleados.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    void Actualiza(){
        Justificantes datosJusitficantes  = new Justificantes();
        controlador.Inserciones consJus  = new controlador.Inserciones();
        datosJusitficantes.setNIDTPJU(Integer.parseInt(CB_justificante.getItemAt(CB_justificante.getSelectedIndex())));
        datosJusitficantes.setCDESJUS(txt_Motivo.getText());
        datosJusitficantes.setCSTATUS(CB_Status.getItemAt(CB_Status.getSelectedIndex()));
        try {
                PreparedStatement pps = cn.prepareStatement(consJus.ModificarJustificante());
                pps.setString(1, datosJusitficantes.getCDESJUS());
                pps.setString(2, datosJusitficantes.getCSTATUS());
                pps.setInt(3, datosJusitficantes.getNIDTPJU());
                pps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Modificado correctamente");
        }catch(SQLException ex) {
                Logger.getLogger(ConsultaEmpleados.class.getName()).log(Level.SEVERE, null, ex);
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_Motivo = new javax.swing.JTextPane();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        CB_Status = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        CB_justificante = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(650, 400));
        getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Clave justificante");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 40, 122, 40);

        txt_Motivo.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jScrollPane1.setViewportView(txt_Motivo);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(210, 80, 250, 130);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Status");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(70, 220, 45, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("Modificar justificante");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(230, 10, 145, 20);

        CB_Status.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        CB_Status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "I" }));
        getContentPane().add(CB_Status);
        CB_Status.setBounds(210, 230, 90, 26);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jButton1.setText("Inicio");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(50, 310, 70, 30);

        btnGuardar.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar);
        btnGuardar.setBounds(280, 270, 110, 30);

        btnConsultar.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsultar);
        btnConsultar.setBounds(150, 310, 100, 30);

        btnModificar.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        btnModificar.setText("Eliminar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificar);
        btnModificar.setBounds(460, 310, 90, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Descripcion");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(60, 80, 85, 40);

        CB_justificante.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        CB_justificante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB_justificanteActionPerformed(evt);
            }
        });
        getContentPane().add(CB_justificante);
        CB_justificante.setBounds(210, 50, 250, 26);

        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 720, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Inicio ini = new Inicio();
        ini.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if(txt_Motivo.getText().equals("")){
             JOptionPane.showMessageDialog(null, "La descripcion del justifiante debe ser llenada");
        }else{
            Actualiza();
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        CatalagoJustificante jus = new CatalagoJustificante();
        jus.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void CB_justificanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB_justificanteActionPerformed

    }//GEN-LAST:event_CB_justificanteActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        Justificantes datosJusitficantes  = new Justificantes();
        datosJusitficantes.setNIDTPJU(Integer.parseInt(CB_justificante.getItemAt(CB_justificante.getSelectedIndex())));
        controlador.Deletes deleHor = new controlador.Deletes();
        try {
             PreparedStatement pps = cn.prepareStatement(deleHor.DeteleJustificante());
             pps.setInt(1, datosJusitficantes.getNIDTPJU());
             pps.executeUpdate();
             JOptionPane.showMessageDialog(this, "Justificante eliminado con exito");
        }catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,"Fallo al eliminar");
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModJustificante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModJustificante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModJustificante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModJustificante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModJustificante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CB_Status;
    private javax.swing.JComboBox<String> CB_justificante;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane txt_Motivo;
    // End of variables declaration//GEN-END:variables
}
