/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import modelo.Horario;

/**
 *
 * @author emmaf
 */
public class ModyElimDiaNoHabil extends javax.swing.JFrame {
controlador.Conexion con = new controlador.Conexion();
        Connection cn  = con.conexion();
    /**
     * Creates new form ModyElimDiaNoHabil
     */
    public ModyElimDiaNoHabil() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Modificar eliminar");
        CB_fechas.removeAllItems();
        llena_fechas();
        llenaStatus();
        //inhabil();
        ImageIcon imagen = new ImageIcon( "src/imagen/fondo.jpg");
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(jLabel2.getWidth(),jLabel2.getHeight(),Image.SCALE_DEFAULT));
        jLabel2.setIcon(icono);
    }
    /*void habil(){
        txt_hdesc.setEditable(true);
        CB_status.setEnabled(true);
    }
    void inhabil(){
        txt_hdesc.setEditable(false);
        CB_status.setEnabled(false);
        jButton1.setEnabled(false);
        
    }*/
    void llena_fechas(){
        controlador.Consultas consfecha;
        consfecha = new controlador.Consultas();
        CB_fechas.removeAllItems();
        Statement st;
        try {
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(consfecha.consultaDiaNhabil());
            while (rs.next()){
                CB_fechas.addItem(rs.getString(1));
            }
        } catch (SQLException ex) {
            Logger.getLogger(RegistrarEmpleado.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
  
    void LlenarDia(){
    Horario datosHorario;
    datosHorario = new Horario();
    controlador.Consultas consHor;
    consHor = new controlador.Consultas();
    Statement st;
    try{
        st = cn.createStatement();
        ResultSet rs = st.executeQuery(consHor.consutaStatusNH(CB_fechas.getItemAt(CB_fechas.getSelectedIndex())));
            //JOptionPane.showMessageDialog(this, "tercero");
             while(rs.next()){
            datosHorario.setCMOTIVO(rs.getString("CMOTIVO"));
            datosHorario.setCSTATUS(rs.getString("CSTATUS"));
            txt_hdesc.setText(datosHorario.getCMOTIVO());
            if (datosHorario.getCSTATUS().compareTo("A")==0){
                     CB_status.setSelectedIndex(0);
                     datosHorario.setCSTATUS("A");
                     }
            if (datosHorario.getCSTATUS().compareTo("I")==0){
                     CB_status.setSelectedIndex(1);
                     datosHorario.setCSTATUS("I");
                     }
             }
              } catch (SQLException ex) {
            Logger.getLogger(ConsultaEmpleados.class.getName()).log(Level.SEVERE, null, ex);
        }
        //if(txt_hdesc.getText().equals("")){
           // JOptionPane.showMessageDialog(null, "Horario no existente");
       // }
    
}
   void llenaStatus(){
     CB_status.removeAllItems();
     CB_status.addItem("A");
     CB_status.addItem("I");
}
   
   void Actualizar(){
    Horario datosHorario;
    datosHorario = new Horario();
    controlador.Inserciones consHor;
    consHor = new controlador.Inserciones();
    datosHorario.setDFECHNL(CB_fechas.getItemAt(CB_fechas.getSelectedIndex()));
    datosHorario.setCSTATUS(CB_status.getItemAt(CB_status.getSelectedIndex()));
    datosHorario.setCMOTIVO(txt_hdesc.getText());
    try {
            PreparedStatement pps = cn.prepareStatement(consHor.ModificarDiaNH());
            pps.setString(1, datosHorario.getCMOTIVO());
            pps.setString(2, datosHorario.getCSTATUS());
            pps.setString(3, datosHorario.getDFECHNL() );
            pps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Modificado correctamente");
    }catch(SQLException ex) {
            Logger.getLogger(ConsultaEmpleados.class.getName()).log(Level.SEVERE, null, ex);
        }
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        CB_fechas = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txt_hdesc = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        CB_status = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 515));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Fecha inhabil");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 70, 100, 20);

        CB_fechas.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        CB_fechas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        CB_fechas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB_fechasActionPerformed(evt);
            }
        });
        getContentPane().add(CB_fechas);
        CB_fechas.setBounds(160, 70, 170, 26);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Motivo");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 120, 100, 20);

        txt_hdesc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(txt_hdesc);
        txt_hdesc.setBounds(160, 110, 280, 110);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Status");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 250, 45, 20);

        CB_status.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        CB_status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "I" }));
        getContentPane().add(CB_status);
        CB_status.setBounds(170, 250, 110, 26);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Guardar ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(180, 310, 90, 28);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("Consultar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(360, 310, 110, 28);

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton5.setText("Inicio");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(20, 310, 70, 28);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setText("Modificar dia no laborable");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(250, 30, 184, 20);

        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, -6, 700, 520);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CB_fechasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB_fechasActionPerformed
        LlenarDia();
    }//GEN-LAST:event_CB_fechasActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        DiaNoHabil dnh = new DiaNoHabil();
        dnh.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       if(txt_hdesc.getText().equals("")){
         JOptionPane.showMessageDialog(null, "La descripcion no debe quedar vacia");  
       }else{
           Actualizar();
       }  
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Inicio ini = new Inicio();
        ini.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModyElimDiaNoHabil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModyElimDiaNoHabil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModyElimDiaNoHabil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModyElimDiaNoHabil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModyElimDiaNoHabil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CB_fechas;
    private javax.swing.JComboBox<String> CB_status;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txt_hdesc;
    // End of variables declaration//GEN-END:variables
}
